### ISSUE TITLE
Funny Stories

### ISSUE THREAD

**Issue by kbodwin** [Cal-Poly-Advanced-R/Week_0#3]
Tell me a funny story of a time your teacher or professor did not understand how to use technology.

**Comment by alliemb** [comment]
I'm honestly **shocked** by how long it took me to think of a story/example! Props to all my tech-savvy teachers/professors! 👍 

...The one example I can remember was in a history class I took years ago. My professor was so frustrated with slides that he opted for monologue style lectures, at what felt like 2x speed. I think I still have a little PTSD from trying to type fast enough to catch up!

**Comment by kabhatia7** [comment]
One time this past quarter, while in the middle of lecture my professor's slides stopped working. The projector just refused to cooperate with 45 minutes left in the lecture. He fiddled with his computer for 15 minutes then said "welp I guess class is over for today", and proceeded to let us all out 30 minutes early.

**Comment by adharlow** [comment]
One time in a communications class during freshman year, the teacher had trouble with the speaker for the computer at her desk. The tech people had to come in multiple times during the quarter because it would work for a week or two then suddenly stop working. She would end up playing the video from the computer and we all had to listen very carefully for the audio since it was coming from the computer audio.

**Comment by rnevils** [comment]
One of my intro to CS professors (now retired I believe) would print out our submitted project code and hand it back to us with the grade on it. Not exactly a failed understanding, but I think it's in a similar vein.

**Comment by jennalandy** [comment]
One of my high school teachers had a *SmartBoard&trade;* in her classroom but lectured with an overhead projector using transparent sheets instead.

**Comment by maggiegreco** [comment]
One time my professor did not understand that you could put music on your [iPhone](https://www.apple.com/iphone/) and was simply amazed that this was possible.

**Comment by sjmarks** [comment]
I had an intro stats professor who used exclusively an overhead projector and transparencies during lecture. They were **_VERY_** adamant about using them. . . challenging to see from a distance.

**Comment by agreen29** [comment]
One time in high school,  one of the students *stole* the **SMART BOARD** remote and kept changing the slides back and forth. It took the entire class for the teacher to figure out what was happening.
>this did not sit well with the teacher

**Comment by srhen** [comment]
My pre-calc teacher started writing with an expo marker on the Smart Board and ***NOBODY*** in the class realized what had happened until she tried to erase it and smeared red ink all over the board.

**Comment by dylan12899** [comment]
I had a professor last quarter who thought someone hacked their computer because the powerpoint presenters view was projecting onto the board and their slides were on their computer screen instead of the other way around like normal (literally a one click fix that they could not figure out)

**Comment by shanealman** [comment]
I had a high school teacher who would keep the volume at the max level on his computer for some reason, and then one time he switched to external speakers to play a video and ended up **blowing out the speakers**.

**Comment by joshkim999** [comment]
My middle school algebra teacher starts saying **"Assume..."** while **writing it on the board**. In the middle, the principal walks in the door. My teacher **stops writing** and looks to start a conversation with the principal, but the principal looks at her with a weird face and all the students were laughing. She turns around and sees **"Ass"** on the board.

**Comment by mitchellbuchan** [comment]
One of my high school teachers did not understand the concept of YouTube autoplay, and accidentally showed us *Tips on Getting Through Your Divorce*.

**Comment by mvonsosen** [comment]
One time I had a professor that knew how to use technology, but didn't understand the concept of *Do Not Disturb* on their messages, so throughout every class we would see messages from various people and know all about his personal life.

**Comment by tciven** [comment]
German professor showing a [video](https://www.youtube.com/watch?v=F1z9tt_2hiM) on youtube in class took forever to realize that there was another [video](https://www.youtube.com/watch?v=TMMqtj9GEAU) in Russian playing in a different tab. I dare you to listen to that bedlam of a combination.

**Comment by mbostrom11** [comment]
One of my high school teachers had forgotten to turn off notifications for his ***personal*** email which resulted in the whole class noticing that he was invited to what sounded like a pretty rowdy party the upcoming weekend.

**Comment by austinschwarz** [comment]
I once had a teacher give a take-home exam with a 'time-limit' but the pdf was available to download and the timer only started once you hit start attempt. So there ended up being no time-limit.

**Comment by afrauenpreis** [comment]
I once had a chemistry professor last year that spent **50%** the lecture time trying to get her PowerPoint presentation to work. She ended up giving up anyway and just rushed us through the material on the chalkboard.

**Comment by sbobba123** [comment]
I once had a professor that didn't know to upload a single document from a file so he would upload the hw and the hw answer key file together.

**Comment by feligonza17** [comment]
# On how my teacher messed up the projection screen

He thought it was the board and started **writing down** with an *expo marker*.

**Comment by dcoliver** [comment]
One time I went to one of the top rated colleges for engineering in the country and I walked into my math class on the first day and they started using chalk

**Comment by erohlf** [comment]
One time my professor couldn't figure out how to give us online quizzes, so they cancelled the whole quiz grade for the **quarter**.

**Comment by Notchanator** [comment]
I **can not** think of a single story/example. But in my high school a few of teachers had really quiet speakers that were impossible to hear, even when they were on max volume.

**Comment by jesprabens** [comment]
Last quarter, my professor, who was in his mid 70's, *really* wanted to give an in-person final because I'm **convinced** he didn't know how to make his final online.  He resorted to assigning an optional five page essay instead. :(

He also used a flip phone and didn't use *any* social media because he wanted to "hide his identity".

**Comment by daniel-broms** [comment]
In high school my computer science teacher claimed that with practice one could understand what was being transmitted over a telephone modem by __listening_ to the sound it made_.  To this day I am not sure if he was kidding or not.

**Comment by giomarini** [comment]
I guess literally **every time** they have to use a projector

**Comment by Sandogom77** [comment]
#Not funny in particular
**Most** of the times people get messed up with projectors and to adapt their *presentation* because different types of equipment do have different **definitions***.

**Comment by DeclanMolony** [comment]
Well, my mom's a teacher, and she's teaching 4th grade via Zoom from home during quarantine. I am her unofficial tech support because I'll be doing schoolwork in my room when I hear from across the house, "DECLANNNN!!!!" Then I have to scamper over there to aid her. (sigh)

**Comment by asarango1** [comment]
_**In high school my English teacher had us listen to a podcast in class, but sometimes she could not figure out how to get the sound to work. On the days the sound didn't work she would assign students to different characters and have them pull up a transcript to read aloud **_

**Comment by asarango1** [comment]
**In high school my English teacher had us listen to a _podcast_ in class, but sometimes she could not figure out how to get the _sound_ to work. On the days the sound didn't work she would assign students to different characters and have them pull up a transcript to read aloud **

**Comment by asarango1** [comment]
**In high school my English teacher had us listen to a podcast in class, but sometimes she could not figure out how to get the sound to work. On the days the sound didn't work she would assign students to different characters and have them pull up a transcript to read aloud**

**Comment by DataKcup** [comment]
When I was in *fifth grade* I was responsible for typing up and editing the kindergarten class' story book they created for their parents because the computer teacher thought I was apparently the best person for the job.

**Comment by jgabalos** [comment]
I was tutoring my nephew on Algebra, when he asked me what does Math mean?  I'm not sure how to answer this, so there was a bit of awkward silence. Then he continued, "Mental Abuse To Humans!"

**Comment by armarqua** [comment]
At Oregon State University, I took a phenomenal *Environmental Physiology* course. The prof was **old school**. He was nearing retirement and refused to use anything other than chalk talks and overhead projectors. :roll_eyes: 

Despite that, he would enthusiastically tell stories about early physiology research and concepts. My personal favorites? 
* Early researchers training dolphins to hold their breath in bathtubs 
* "If any wolf managed to get frostbite, he'd be so ashamed that he'd have to turn in his wolf badge."

**Comment by alexjj** [comment]
When I was at high school I had one of these watches:
![image](https://user-images.githubusercontent.com/440939/83609409-2a24cc00-a576-11ea-82f0-2edc88618272.png)
Needless to say the teacher had no idea why the volume kept changing, the VHS (lol yes) kept rewinding and other general changes. Obviously the whole class knew but kept quiet. 

Now that I'm in the "real world", I can assure you the lack of technology understanding doesn't stop at school.

**Comment by cnillaga1** [comment]
My second year here at *Cal Poly* one of my professors was having trouble getting his slides to show through the projector. The **remaining time** left in class we had we watched him try and to figure out how to get his slides on the board.

**Comment by samoomiller** [comment]
My brother, who is a freshman in high school, just told me a funny story about how his professor administered a midterm and accidentally made **every** answer to the test **A**.

**Comment by Beabaea** [comment]
When students were giving power point presentations and my professor could not how to *connect the cables* to show the presentation slide

**Comment by hasiegler** [comment]
I can't think of a particular story, but in elementary school and junior high I can remember many teachers not understanding how to use the **projector** in the classroom.

**Comment by jamesugawara** [comment]
Last quarter an older professor could not figure out how to show his slides through the projector and would have a maintenance guy come in everyday. Every time, the maintenance guy would show the professor what he needed to do to get it to work but he'd forget by the next day.

**Comment by michaelaehlers** [comment]
A professor I had fall quarter wasn't able to figure out how to open a canvas midterm to us that we were taking in person so we all showed up to class ready to take it and couldn't! We had to wait a week to take the midterm and ended up having to take it at home!

**Comment by Luke-Conn** [comment]
In that first spring quarter online I had a final where every answer was A. Apparently nobody wanted to look a gift horse in the mouth because I never heard from the prof about what must have been a 99% class average.

**Comment by Chaicow** [comment]
One of my professors didn't know how to enter grades onto Canvas so periodically, he sent us all an excel spreadsheet with all of our grades and EMPL ids. Once, he forgot to delete all of our names so everyone in the class had access to everyone else's EMPL ID and grade in the class. **VERY SECURE**

**Comment by trententso** [comment]
Last quarter, my professor did not know how to turn on the volume for videos, so every video we just read the **subtitles**.

**Comment by sophiebmoore00** [comment]
A professor needed to assign groups for a group project through canvas and didn't know how, so he created an assignment worth 5 points and your grade out of 5 *was your group number*.

**Comment by DaneDorm** [comment]
Last fall, I had a professor that used a private Facebook page to make announcements and post discussions. And these were important announcements and discussions that had graded participation. So when Facebook crashed in October and was out for a day, we couldn't access any class information and had to scramble to get our assignments in.

**Comment by rachael-ryan** [comment]
One time my professor's wifi connection was poor and we could not hear him. When we brought it to his attention, he got mad because he thought we were lying to him since things seemed fine on his end. He didn't realize that his connection was the problem!

**Comment by kbodwin** [comment]
> Last fall, I had a professor that used a private Facebook page to make announcements and post discussions. And these were important announcements and discussions that had graded participation. So when Facebook crashed in October and was out for a day, we couldn't access any class information and had to scramble to get our assignments in.

Okay, this is officially the weirdest one I've heard.  I'm all about the Millennial and older tech (Facebook, gchat....) - but I don't use if for class!  Wow.

**Comment by mknauss58** [comment]
A few quarters ago, one of my professors said that he had to redo a lecture video that he was recording for an asynchronous class because he forgot to press record before starting.

**Comment by Ammlakh** [comment]
During the last quarter, one of my professors did not understand how to share his screen during zoom, so whenever he would change to another tab to teach we would see **only the original tab.**

**Comment by knag7** [comment]
Last winter, one of my teachers would always forget they were muted on **Zoom** and we always had to remind them to un-mute themself.

**Comment by miloweller1** [comment]
My favorite was when everybody was getting used to zoom and professors would often forgot to unmute themselves

**Comment by BRANDONKIM84921** [comment]
One time, my calculus professor didn't mute himself on zoom and we heard him fart. [Professor using zoom](https://media.istockphoto.com/id/1223604450/photo/cheerful-professor-communicate-with-pupils-over-video-call.jpg?s=612x612&w=0&k=20&c=2yXLsSpsJvIrJao-mVUl88BpKeoNd4Dl93ls23hn0j0=)

**Comment by cstivers** [comment]
I had a teacher in high school who struggled to **use the projector** everyday. She always had to call the technician to figure out how to work it.

**Comment by ajt7** [comment]
In high school, my teacher accidentally used an expo marker on a smart board. For the rest of the school year there was a huge black smudge on the screen.

**Comment by wdemers** [comment]
Not just did the goat Steve Rein **never** wear shoes to class but we also would spend at least 15 minutes every class period with him trying to turn the projector on. He called IT multiple times through the quarter.

**Comment by shreyaaar** [comment]
One of my professors could not figure out how to use canvas to save his life. One of the times I went into his office hours, he had me and a few other students 'fix' canvas for him (week 8).

**Comment by SamuelTodd** [comment]
During high school, one of my teachers lectured for the first 20 minutes of class *without turning on their camera or microphone*.

**Comment by gavinemartinez** [comment]
One of my professors did an entire lecture with no sound and the class muted. The whole time we were typing in the chat but he couldn't see it. After an hour there were 5/30 people left in the class.

**Comment by josh-rowe** [comment]
One of the professors I do research with could never figure out how to allow participants to share their screens in zoom calls, so they would re-start the meeting or make students the meeting host so they could screen share, instead of checking the box which would allow participants to share screens.

**Comment by CassJG** [comment]
One of my professors **teaching CPE 101** would mute herself constantly on Zoom **and** wouldn't look at the chat to see the many people telling her she was muted.

**Comment by cannsemestawa** [comment]
Teacher never set the correct permissions on Google Drive. Students could not work on the assignment and/or the main document would have _unintended changes_.
